name: EAD
version: 1.2
main: com.excrele.antidupe.EADPlugin
api-version: 1.21
author: Excrele
description: Excrele Anti Dupe - A plugin to prevent item and block duplication exploits in Minecraft servers.

# List of permissions
permissions:
  ead.bypass:
    description: Allows players to bypass anti-dupe measures.
    default: op
  ead.message:
    description: Allows players to receive alert messages about potential duping attempts.
    default: op